# This is a basic workflow to help you get started with Actions

name: tnn-android-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "env_prepare"
  env_preprare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - name: pre-commit check
      run:
        cd .github/workflows && ./pre-commit-job.sh

    - name: python unit test
      run:
        .github/workflows/unit-test-job.sh
        


  tnn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tnn build
      run: cd tnn && ./build.sh

  models:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: download official models
      run: cd models && ./download.sh

